# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default="Customer's Address", max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default="Customer's Name", max_length=250),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default="Customer's Username", max_length=100),
        ),
    ]
