# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20160421_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(max_length=3),
        ),
    ]
