# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20160421_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='history',
        ),
        migrations.RemoveField(
            model_name='history',
            name='name',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
