# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20160421_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_chicken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_fries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
