# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20160422_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
