# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_customer_is_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='username',
        ),
    ]
