# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20160422_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(default='', max_length=500),
        ),
    ]
