# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20160425_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
